spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: bank
  application:
    name: MongoBank

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: INFO
      mongodb:
        driver: DEBUG



