import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Persistence',
      items: ['persistence/persist', 'persistence/query','persistence/update_schema'],
    },
    {
      type: 'category',
      label: 'Relationships',
      items: ['relationships/customer_and_account', 'relationships/transaction','relationships/acid', 'relationships/subset'],
    },
    {
      type: 'category',
      label: 'Advanced',
      items: ['advanced/polymorphic', 'advanced/full_text_search'],
    },
  ],
};

export default sidebars;
